import type { Metadata } from "next";

import "./_styles/reset.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";
import Header from "./(todayhouse)/_components/Header";

import CombineProviders from "@/providers/CombineProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Header />
        <CombineProviders>{children}</CombineProviders>
      </body>
    </html>
  );
}
