import type { Metadata } from "next";
import { MswProvider } from "@/providers/MswProvider";
import ReactQueryProvider from "@/providers/ReactQueryProvider";
import "./_styles/reset.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ReactQueryProvider>
          <MswProvider />
          {children}
        </ReactQueryProvider>
      </body>
    </html>
  );
}
